# Generated by Django 4.2.5 on 2023-09-21 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_car_brand_alter_brand_image_alter_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='engine_capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(max_length=40, verbose_name='Engine Capacity')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='engine_capacity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='sell.engine_capacity'),
        ),
    ]
